spring:
  #  datasource:
  #    url: jdbc:postgresql://10.178.0.13:5432/postgresql
  #    username: postgresql
  #    password: postgrespassword
  #  jpa:
  #    show-sql: false
  #    hibernate:
  #      dialect: org.hibernate.dialect.PostgreSQLDialect
  #      ddl-auto: update
  rabbitmq:
    host: 10.178.0.14
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.5,10.146.0.2,10.146.0.4,10.146.0.6
      ports:
